let raquettes = [
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. BYPE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1023",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 18,
		"adherence": 19,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "48",
		"prix": 43.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. HEXER DURO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1055",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 43,
		"stockage": "Oui",
		"page": "I",
		"prix": 44.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA EUROPE H",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1126",
		"epaisseur": "2.0/max",
		"rapidite": 20,
		"adherence": 20,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "56",
		"prix": 44.9
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA PRO H",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1128",
		"epaisseur": "2.0/max",
		"rapidite": 20,
		"adherence": 20,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47,
		"stockage": "Oui",
		"page": "56",
		"prix": 48.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. AURUS SELECT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=104",
		"epaisseur": "1.7/1.9/2.1/max",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "13",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION EL-P",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=111",
		"epaisseur": "1.8/2.0/2.2",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 44,
		"stockage": "Oui",
		"page": "8",
		"prix": 53.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. SINUS ALPHA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=126",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "14",
		"prix": 47.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. QUANTUM X PRO SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=151",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "11",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM BIGSLAM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=735",
		"epaisseur": "1.9/2.1/max",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "36",
		"prix": 55.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUEFIRE M2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=797",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "22",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 15 STICKY",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=863",
		"epaisseur": "2.0/max",
		"rapidite": 21,
		"adherence": 19,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 52.5,
		"stockage": "Oui",
		"page": " ",
		"prix": 59.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. OURAGAN 42",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=922",
		"epaisseur": "1.9/2.1",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Oui",
		"page": "104",
		"prix": 43.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. MEGASPIN 40",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=946",
		"epaisseur": "1.9/2.1",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "I",
		"prix": 46.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. HEXER POWERGRIP SFX",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1009",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 21,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "60",
		"prix": 49.95
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION EL-S",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=108",
		"epaisseur": "1.8/2.0/2.2",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "8",
		"prix": 53.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. NIMBUS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=130",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21.5,
		"adherence": 18.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "15",
		"prix": 45.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION FX-D",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=145",
		"epaisseur": "2.0/2.2",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 44,
		"stockage": "Oui",
		"page": "53",
		"prix": 56.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID MK FX",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=163",
		"epaisseur": "2.0/max",
		"rapidite": 21.5,
		"adherence": 20.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "23",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID K3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=171",
		"epaisseur": "2.0/max",
		"rapidite": 21.5,
		"adherence": 20.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 53,
		"stockage": "Oui",
		"page": "57",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM Z3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=734",
		"epaisseur": "2.1/max",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 55.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. COPPA X2 (platin soft)",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=776",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21.5,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "37",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. POWERFEELING 43",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=941",
		"epaisseur": "2.1",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 43,
		"stockage": "Oui",
		"page": "I",
		"prix": 48.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. POWERDREAM 42",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=942",
		"epaisseur": "1.9/max",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Oui",
		"page": "103",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R42",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1021",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Oui",
		"page": "103",
		"prix": 54.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1101",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 21.5,
		"adherence": 19,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA KOREA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1127",
		"epaisseur": "max",
		"rapidite": 21.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "56",
		"prix": 44.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID MK",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=162",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 20,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 48,
		"stockage": "Oui",
		"page": "26",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "STIGA",
		"designation": "REV. DNA PLATINUM S",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=465",
		"epaisseur": "2.1/2.3",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "89",
		"prix": 69.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. TRONIX CMD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=626",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 43,
		"stockage": "Oui",
		"page": "53",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ CMD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=694",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 62.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTAR A3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=709",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "34",
		"prix": 69.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUEGRIP C2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=742",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 55,
		"stockage": "Oui",
		"page": "37",
		"prix": 55.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUEGRIP S1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=746",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "24",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BARACUDA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=771",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "25",
		"prix": 45.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. VENTUS EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=838",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "94",
		"prix": 47.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 20 EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=842",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 20,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "57",
		"prix": 57.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER V42",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1018",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Oui",
		"page": "58",
		"prix": 54.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. NUZN 50",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1025",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 20.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "43",
		"prix": 79.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. HEXER GRIP",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1063",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "60",
		"prix": 49.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA X",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1124",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 22,
		"adherence": 19,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 43.9
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA ASIA H",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1125",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 20,
		"controle": 12,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "56",
		"prix": 44.9
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. OMEGA VII EURO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1133",
		"epaisseur": "2.0/max",
		"rapidite": 22,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "96",
		"prix": 57.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. AURUS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=115",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "12",
		"prix": 45.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION EL-D",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=144",
		"epaisseur": "2.0/2.2",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 46,
		"stockage": "Oui",
		"page": "53",
		"prix": 56.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID K3 PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=157",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 20.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 55,
		"stockage": "Oui",
		"page": "22",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID MK PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=173",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 20.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 51,
		"stockage": "Oui",
		"page": "23",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "STIGA",
		"designation": "REV. DNA DRAGON GRIP",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=463",
		"epaisseur": "2.3",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 55,
		"stockage": "Oui",
		"page": "90",
		"prix": 59.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. TRONIX ZGR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=628",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 56,
		"stockage": "Oui",
		"page": "53",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. RHYZEN CMD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=698",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "81",
		"prix": 39.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM Z2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=733",
		"epaisseur": "2.1/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 55.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 22 DOUBLE EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=841",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 12,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "144",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER C45",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1005",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "43",
		"prix": 64.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER C48",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1007",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 48,
		"stockage": "Oui",
		"page": "100",
		"prix": 64.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R47",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1020",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47,
		"stockage": "Oui",
		"page": "59",
		"prix": 54.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. NUZN 55",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1026",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 20.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 55,
		"stockage": "Oui",
		"page": "43",
		"prix": 79.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R45",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1041",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "57",
		"prix": 62.95
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. HEXER POWERGRIP",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1062",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "60",
		"prix": 49.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA TOUR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1119",
		"epaisseur": "2.0/max",
		"rapidite": 22.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "98",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. AURUS PRIME",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=103",
		"epaisseur": "1.7/1.9/2.1/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "13",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION MX-P",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=110",
		"epaisseur": "1.6/1.8/2.0/2.2",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "9",
		"prix": 53.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. SINUS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=125",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 23,
		"adherence": 19,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "14",
		"prix": 47.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. QUANTUM X PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=189",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "57",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. TRONIX ACC",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=627",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "53",
		"prix": 49.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ ACC",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=692",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 62.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. RHYZEN FIRE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=697",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "123",
		"prix": 39.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUEFIRE M1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=796",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 20 DOUBLE EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=840",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 52.5,
		"stockage": "Oui",
		"page": "144",
		"prix": 57.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 15 STIFF",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=862",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "96",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R 48",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1029",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 48,
		"stockage": "Oui",
		"page": "57",
		"prix": 62.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. VEGA ASIA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1122",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 23,
		"adherence": 19,
		"controle": 12,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. OMEGA VII PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1132",
		"epaisseur": "2.0/max",
		"rapidite": 23,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "96",
		"prix": 57.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION MX-S",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=109",
		"epaisseur": "1.6/1.8/2.0/2.2",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 46.5,
		"stockage": "Oui",
		"page": "9",
		"prix": 53.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ ZGX",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=618",
		"epaisseur": "2.0/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 53,
		"stockage": "Oui",
		"page": "51",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTAR A2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=708",
		"epaisseur": "2.0/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "34",
		"prix": 69.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM PRO AM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=724",
		"epaisseur": "2.0/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "36",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM Z1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=732",
		"epaisseur": "2.1/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 55.9
	},
	{
		"categorie": "off+",
		"marque": "VICTAS",
		"designation": "REV. V 15 EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=860",
		"epaisseur": "2.0/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "96",
		"prix": 52.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER C53",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1006",
		"epaisseur": "2.0/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 53,
		"stockage": "Oui",
		"page": "100",
		"prix": 64.95
	},
	{
		"categorie": "off+",
		"marque": "XIOM",
		"designation": "REV. JEKYLL HYDE V47,5",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1138",
		"epaisseur": "2.1/max",
		"rapidite": 23.5,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "95",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION MX-P50",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=100",
		"epaisseur": "2.2",
		"rapidite": 24,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "9",
		"prix": 56.9
	},
	{
		"categorie": "off+",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION MX-D",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=199",
		"epaisseur": "2.0/2.2",
		"rapidite": 24,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 51,
		"stockage": "Oui",
		"page": "9",
		"prix": 56.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ AGR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=693",
		"epaisseur": "2.0/max",
		"rapidite": 24,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "I",
		"prix": 62.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. ULTIMATE POWER 47,5",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=947",
		"epaisseur": "2.1",
		"rapidite": 24,
		"adherence": 19.5,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.7,
		"stockage": "Oui",
		"page": "159",
		"prix": 54.9
	},
	{
		"categorie": "off+",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R53",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1014",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 24,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 53,
		"stockage": " ",
		"page": "56",
		"prix": 62.95
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ ZGR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=695",
		"epaisseur": "2.0/max",
		"rapidite": 24.5,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 57.5,
		"stockage": "Oui",
		"page": "80",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTORM PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=738",
		"epaisseur": "2.0/max",
		"rapidite": 24.5,
		"adherence": 19.5,
		"controle": 12,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "36",
		"prix": 64.9
	},
	{
		"categorie": "off+",
		"marque": "JOOLA",
		"designation": "REV. DYNARYZ INFERNO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=617",
		"epaisseur": "2.0/max",
		"rapidite": 25,
		"adherence": 19.5,
		"controle": 11.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "51",
		"prix": 69.9
	},
	{
		"categorie": "off+",
		"marque": "DONIC",
		"designation": "REV. BLUESTAR A1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=707",
		"epaisseur": "2.0/max",
		"rapidite": 25,
		"adherence": 19.5,
		"controle": 12,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 52.5,
		"stockage": "Oui",
		"page": "23",
		"prix": 69.9
	},
	{
		"categorie": "off+",
		"marque": "BANCO",
		"designation": "REV. ULTIMATE POWER 50",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=948",
		"epaisseur": "2.1",
		"rapidite": 25,
		"adherence": 19.5,
		"controle": 12.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "66",
		"prix": 54.9
	},
	{
		"categorie": "off",
		"marque": "ANDRO",
		"designation": "REV. GTT 45",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1067",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16.5,
		"adherence": 18.5,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "106",
		"prix": 37.95
	},
	{
		"categorie": "off",
		"marque": "ANDRO",
		"designation": "REV. BYPE SFX",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1024",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 17,
		"adherence": 19,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "48",
		"prix": 43.95
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VJC 07 STICKY EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=873",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 17.5,
		"adherence": 19.5,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Non",
		"page": "I",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "XIOM",
		"designation": "REV. VEGA INTRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1123",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 17.5,
		"adherence": 19,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 34.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. NIMBUS SOUND",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=128",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 18,
		"adherence": 18.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 32.5,
		"stockage": "Oui",
		"page": "15",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. DESTO F3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=706",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 18,
		"adherence": 18,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "27",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. VARIO BIGSLAM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=768",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 18,
		"adherence": 18.5,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "41",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "BANCO",
		"designation": "REV. PUISSANCE 37",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=931",
		"epaisseur": "1.8/2.0",
		"rapidite": 18,
		"adherence": 19,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37,
		"stockage": "Oui",
		"page": "105",
		"prix": 42.9
	},
	{
		"categorie": "off",
		"marque": "DHS",
		"designation": "REV. NEO HURRICANE 3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1241",
		"epaisseur": "2.1",
		"rapidite": 18,
		"adherence": 19,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "I",
		"prix": 35.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. AURUS SOUND",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=117",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 18.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "12",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "JOOLA",
		"designation": "REV. RHYZEN ICE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=696",
		"epaisseur": "2.0/max",
		"rapidite": 18.5,
		"adherence": 19.5,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "123",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. ACUDA S3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=782",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 18.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "39",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "ANDRO",
		"designation": "REV. HEXER POWERSPONGE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1054",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 18.5,
		"adherence": 19.5,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Oui",
		"page": "I",
		"prix": 49.95
	},
	{
		"categorie": "off",
		"marque": "DR NEUBAUER",
		"designation": "REV. DOMINANCE SPIN",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1366",
		"epaisseur": "1.3/1.5/1.8/2.1",
		"rapidite": 18.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Oui",
		"page": "I",
		"prix": 42.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. AURUS SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=116",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "12",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. SINUS SOUND",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=124",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 19,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "14",
		"prix": 47.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. NIMBUS SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=129",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 18.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "15",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "YASAKA",
		"designation": "REV. MARK V HPS SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=337",
		"epaisseur": "2.0/max",
		"rapidite": 19,
		"adherence": 18,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. DESTO F2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=704",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 18,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "40",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VENTUS LIMBER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=833",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "94",
		"prix": 42.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VS 402 LIMBER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=865",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "95",
		"prix": 47.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VJ 07 LIMBER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=871",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19,
		"adherence": 19,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "94",
		"prix": 44.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. TRIPLE EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=876",
		"epaisseur": "2.0/max",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 55,
		"stockage": "Oui",
		"page": "95",
		"prix": 48.9
	},
	{
		"categorie": "off",
		"marque": "ANDRO",
		"designation": "REV. RASANTER R37",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1022",
		"epaisseur": "1.7/2.0/max",
		"rapidite": 19,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37,
		"stockage": "Oui",
		"page": "59",
		"prix": 54.95
	},
	{
		"categorie": "off",
		"marque": "XIOM",
		"designation": "REV. VEGA ELITE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1103",
		"epaisseur": "2.0/max",
		"rapidite": 19,
		"adherence": 19,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. DESTO F1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=705",
		"epaisseur": "2.0/max",
		"rapidite": 19.5,
		"adherence": 18,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "26",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. ACUDA S2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=781",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19.5,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "25",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. BARACUDA BIGSLAM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=785",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "39",
		"prix": 45.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VS 402 DOUBLE EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=866",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 19.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "95",
		"prix": 47.9
	},
	{
		"categorie": "off",
		"marque": "ANDRO",
		"designation": "REV. HEXER GRIP SFX",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1008",
		"epaisseur": "1.7/1.9/2.1",
		"rapidite": 19.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "60",
		"prix": 49.95
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION FX-P",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=112",
		"epaisseur": "1.8/2.0/2.2",
		"rapidite": 20,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "8",
		"prix": 53.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. DESTO F1 PLUS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=702",
		"epaisseur": "2.0/max",
		"rapidite": 20,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "I",
		"prix": 42.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. COPPA X3 (silver)",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=777",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20,
		"adherence": 19,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 52.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. BLUEFIRE M3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=798",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "38",
		"prix": 52.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. VENTUS STIFF",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=832",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20,
		"adherence": 19.5,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "94",
		"prix": 42.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. V 01 LIMBER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=851",
		"epaisseur": "2.0/max",
		"rapidite": 20,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "96",
		"prix": 48.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. TRIPLE DOUBLE EXTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=875",
		"epaisseur": "2.0/max",
		"rapidite": 20,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 57.5,
		"stockage": "Oui",
		"page": "95",
		"prix": 52.9
	},
	{
		"categorie": "off",
		"marque": "XIOM",
		"designation": "REV. VEGA EUROPE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1102",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. EVOLUTION FX-S",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=107",
		"epaisseur": "1.8/2.0/2.2",
		"rapidite": 20.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Oui",
		"page": "8",
		"prix": 53.9
	},
	{
		"categorie": "off",
		"marque": "TIBHAR",
		"designation": "REV. HYBRID K1 EUROPE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=168",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20.5,
		"adherence": 20,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "11",
		"prix": 48.9
	},
	{
		"categorie": "off",
		"marque": "YASAKA",
		"designation": "REV. MARK V HPS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=336",
		"epaisseur": "2.0/max",
		"rapidite": 20.5,
		"adherence": 18,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 50,
		"stockage": "Oui",
		"page": "I",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "DONIC",
		"designation": "REV. BLUEGRIP S2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=799",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20.5,
		"adherence": 19.5,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "37",
		"prix": 49.9
	},
	{
		"categorie": "off",
		"marque": "VICTAS",
		"designation": "REV. V 15 LIMBER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=861",
		"epaisseur": "2.0/max",
		"rapidite": 20.5,
		"adherence": 19.5,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "96",
		"prix": 52.9
	},
	{
		"categorie": "off",
		"marque": "XIOM",
		"designation": "REV. VEGA JAPAN",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1100",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 20.5,
		"adherence": 19,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "I",
		"prix": 44.9
	},
	{
		"categorie": "off-",
		"marque": "DONIC",
		"designation": "REV. VARIO SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=713",
		"epaisseur": "1.5/1.8/2.0/max",
		"rapidite": 15,
		"adherence": 18,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Non",
		"page": "41",
		"prix": 35.9
	},
	{
		"categorie": "off-",
		"marque": "VICTAS",
		"designation": "REV. VS 401",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=853",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 15,
		"adherence": 19,
		"controle": 16.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 57.5,
		"stockage": "Oui",
		"page": "95",
		"prix": 47.9
	},
	{
		"categorie": "off-",
		"marque": "ANDRO",
		"designation": "REV. GOOD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1084",
		"epaisseur": "1.8/2.1",
		"rapidite": 15,
		"adherence": 18.5,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "I",
		"prix": 32.95
	},
	{
		"categorie": "off-",
		"marque": "ANDRO",
		"designation": "REV. IMPULS SPEED",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1089",
		"epaisseur": "1.8/2.1",
		"rapidite": 15.5,
		"adherence": 19,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 32.5,
		"stockage": "Oui",
		"page": "61",
		"prix": 42.95
	},
	{
		"categorie": "off-",
		"marque": "YASAKA",
		"designation": "REV. MARK V GPS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=325",
		"epaisseur": "1.5/1.8/2.0/max",
		"rapidite": 16,
		"adherence": 17,
		"controle": 14,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "JOOLA",
		"designation": "REV. SAMBA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=632",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16,
		"adherence": 17,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "I",
		"prix": 34.9
	},
	{
		"categorie": "off-",
		"marque": "DONIC",
		"designation": "REV. VARIO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=714",
		"epaisseur": "1.5/1.8/2.0/max",
		"rapidite": 16,
		"adherence": 18,
		"controle": 13.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "41",
		"prix": 35.9
	},
	{
		"categorie": "off-",
		"marque": "VICTAS",
		"designation": "REV. VENTUS REGULAR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=837",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 16,
		"adherence": 18.5,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "94",
		"prix": 25.9
	},
	{
		"categorie": "off-",
		"marque": "VICTAS",
		"designation": "REV. VJ 07 REGULAR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=870",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16,
		"adherence": 19,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "94",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "ANDRO",
		"designation": "REV. GTT 40",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1066",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16,
		"adherence": 18.5,
		"controle": 16.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "61",
		"prix": 37.95
	},
	{
		"categorie": "off-",
		"marque": "TIBHAR",
		"designation": "REV. RAPID SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=153",
		"epaisseur": "1.6/1.8/2.0/max",
		"rapidite": 16.5,
		"adherence": 17,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "16",
		"prix": 36.9
	},
	{
		"categorie": "off-",
		"marque": "DONIC",
		"designation": "REV. DESTO F4",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=700",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16.5,
		"adherence": 18.5,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "40",
		"prix": 35.9
	},
	{
		"categorie": "off-",
		"marque": "VICTAS",
		"designation": "REV. VENTUS REGULAR ALPHA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=839",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 16.5,
		"adherence": 19,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "59",
		"prix": 29.9
	},
	{
		"categorie": "off-",
		"marque": "VICTAS",
		"designation": "REV. TRIPLE REGULAR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=877",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 16.5,
		"adherence": 19.5,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "95",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "ANDRO",
		"designation": "REV. IMPULS POWERSPONGE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1090",
		"epaisseur": "1.8/2.1",
		"rapidite": 16.5,
		"adherence": 19,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "61",
		"prix": 48.95
	},
	{
		"categorie": "off-",
		"marque": "DR NEUBAUER",
		"designation": "REV. DOMINATION SPEED SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1360",
		"epaisseur": "1.5/1.8/2.0/2.2",
		"rapidite": 16.5,
		"adherence": 18.5,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "I",
		"prix": 42.9
	},
	{
		"categorie": "off-",
		"marque": "TIBHAR",
		"designation": "REV. RAPID",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=155",
		"epaisseur": "1.6/1.8/2.0/max",
		"rapidite": 17,
		"adherence": 17,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "16",
		"prix": 36.9
	},
	{
		"categorie": "off-",
		"marque": "TIBHAR",
		"designation": "REV. SPEEDY SPIN",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=172",
		"epaisseur": "1.0/1.3/1.5/1.7/1.9/2.1",
		"rapidite": 17,
		"adherence": 17,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "16",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "YASAKA",
		"designation": "REV. MARK V",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=323",
		"epaisseur": "1.5/1.8/2.0/max",
		"rapidite": 17,
		"adherence": 17,
		"controle": 13,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "I",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "JOOLA",
		"designation": "REV. MICRON",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=609",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 17,
		"adherence": 18.5,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "54",
		"prix": 29.9
	},
	{
		"categorie": "off-",
		"marque": "DONIC",
		"designation": "REV. AKKADI TAICHI",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=769",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 17,
		"adherence": 19,
		"controle": 14.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 47.5,
		"stockage": "Non",
		"page": "42",
		"prix": 24.9
	},
	{
		"categorie": "off-",
		"marque": "BANCO",
		"designation": "REV. EXCELLENCE 37",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=928",
		"epaisseur": "1.8/2.1",
		"rapidite": 17,
		"adherence": 18,
		"controle": 15,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37,
		"stockage": "Non",
		"page": "106",
		"prix": 34.9
	},
	{
		"categorie": "off-",
		"marque": "BANCO",
		"designation": "REV. FEEL ENERGIE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=950",
		"epaisseur": "1.8/2.1",
		"rapidite": 17,
		"adherence": 19,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Oui",
		"page": "107",
		"prix": 36.9
	},
	{
		"categorie": "off-",
		"marque": "DONIC",
		"designation": "REV. DESTO F3 BIGSLAM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=770",
		"epaisseur": "1.8/2.0/max",
		"rapidite": 17.5,
		"adherence": 18,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 32.5,
		"stockage": "Oui",
		"page": "40",
		"prix": 39.9
	},
	{
		"categorie": "off-",
		"marque": "BANCO",
		"designation": "REV. PUISSANCE 32",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=936",
		"epaisseur": "1.8/2.0",
		"rapidite": 17.5,
		"adherence": 19,
		"controle": 15.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 32,
		"stockage": "Oui",
		"page": "105",
		"prix": 42.9
	},
	{
		"categorie": "all off",
		"marque": "TIBHAR",
		"designation": "REV. LEGEND",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=143",
		"epaisseur": "1.6/1.8/2.0/max",
		"rapidite": 14,
		"adherence": 16,
		"controle": 17.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "I",
		"prix": 22.9
	},
	{
		"categorie": "all off",
		"marque": "BANCO",
		"designation": "REV. FEELING",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=903",
		"epaisseur": "1.2/1.5/1.8/2.1",
		"rapidite": 14,
		"adherence": 19,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "106",
		"prix": 34.9
	},
	{
		"categorie": "all off",
		"marque": "TIBHAR",
		"designation": "REV. VOLCANO+",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=159",
		"epaisseur": "1.6/1.8/2.0/max",
		"rapidite": 14.5,
		"adherence": 17,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Non",
		"page": "I",
		"prix": 22.9
	},
	{
		"categorie": "all off",
		"marque": "TIBHAR",
		"designation": "REV. VARI SPIN D.TECS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=198",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 14.5,
		"adherence": 18.5,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 32.5,
		"stockage": "Oui",
		"page": "17",
		"prix": 37.9
	},
	{
		"categorie": "all off",
		"marque": "DONIC",
		"designation": "REV. QUATTRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=758",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": 14.5,
		"adherence": 19,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Non",
		"page": "28",
		"prix": 38.9
	},
	{
		"categorie": "all off",
		"marque": "BANCO",
		"designation": "REV. VARIATION ENERGIE",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=916",
		"epaisseur": "1.5/1.8/2.1",
		"rapidite": 14.5,
		"adherence": 18,
		"controle": 18.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "107",
		"prix": 35.9
	},
	{
		"categorie": "all",
		"marque": "BANCO",
		"designation": "REV. PERFECT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=911",
		"epaisseur": "1.5",
		"rapidite": 11,
		"adherence": 13,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "I",
		"prix": 16.9
	},
	{
		"categorie": "all",
		"marque": "TIBHAR",
		"designation": "REV. TIBHAR GAME",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=113",
		"epaisseur": "2.0",
		"rapidite": 13,
		"adherence": 15,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": " ",
		"prix": 31.9
	},
	{
		"categorie": "all",
		"marque": "TIBHAR",
		"designation": "REV. VARI SPIN",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=174",
		"epaisseur": "1.2/1.5/1.8/2.0/max",
		"rapidite": 13,
		"adherence": 19,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "17",
		"prix": 36.9
	},
	{
		"categorie": "all",
		"marque": "BANCO",
		"designation": "REV. ALLSTAR",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=909",
		"epaisseur": "1.5/1.8",
		"rapidite": 13,
		"adherence": 15,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "106",
		"prix": 22.9
	},
	{
		"categorie": "all",
		"marque": "DONIC",
		"designation": "REV. LIGA PLUS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=725",
		"epaisseur": "1.8/2.0",
		"rapidite": 13.5,
		"adherence": 18,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Non",
		"page": "I",
		"prix": 29.9
	},
	{
		"categorie": "all",
		"marque": "FRIENDSHIP",
		"designation": "REV. FRIENDSHIP 729",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1259",
		"epaisseur": "1.5/2.0",
		"rapidite": 13.5,
		"adherence": 18,
		"controle": 16,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 44,
		"stockage": "Non",
		"page": "I",
		"prix": 14.95
	},
	{
		"categorie": "all",
		"marque": "CORNILLEAU",
		"designation": "REV. START UP EVO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1277",
		"epaisseur": "1.8",
		"rapidite": 13.5,
		"adherence": 17,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Non",
		"page": "72",
		"prix": 19.9
	},
	{
		"categorie": "initiation",
		"marque": "TIBHAR",
		"designation": "REV. LEARN SPIN",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=185",
		"epaisseur": "1.5",
		"rapidite": 6,
		"adherence": 8,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 30,
		"stockage": "Non",
		"page": "I",
		"prix": 12.9
	},
	{
		"categorie": "initiation",
		"marque": "TIBHAR",
		"designation": "REV. NORM",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=186",
		"epaisseur": "1.5",
		"rapidite": 10,
		"adherence": 11,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "I",
		"prix": 11.9
	},
	{
		"categorie": "défense",
		"marque": "TIBHAR",
		"designation": "REV. SUPER DEFENSE 40 SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=194",
		"epaisseur": "1.3/1.6",
		"rapidite": 10.5,
		"adherence": 19,
		"controle": 18.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "I",
		"prix": 50.9
	},
	{
		"categorie": "défense",
		"marque": "DR NEUBAUER",
		"designation": "REV. DEFENCE MASTER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1371",
		"epaisseur": "1.0/1.2/1.5",
		"rapidite": 10.5,
		"adherence": 19.5,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "155",
		"prix": 42.9
	},
	{
		"categorie": "défense",
		"marque": "TIBHAR",
		"designation": "REV. SUPER DEFENSE 40",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=193",
		"epaisseur": "0.5/0.9/1.3/1.5/1.7/1.9",
		"rapidite": 11,
		"adherence": 19,
		"controle": 18,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 40,
		"stockage": "Non",
		"page": "I",
		"prix": 50.9
	},
	{
		"categorie": "défense",
		"marque": "DONIC",
		"designation": "REV. SLICE 40 CS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=717",
		"epaisseur": "1.3/1.5",
		"rapidite": 11,
		"adherence": 19.5,
		"controle": 17,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Oui",
		"page": "37",
		"prix": 39.9
	},
	{
		"categorie": "défense",
		"marque": "DONIC",
		"designation": "REV. SLICE 40 CD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=736",
		"epaisseur": "1.2/1.5/1.8",
		"rapidite": 11.5,
		"adherence": 19,
		"controle": 17.5,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "42",
		"prix": 39.9
	},
	{
		"categorie": "anti-top",
		"marque": "TIBHAR",
		"designation": "REV. ELLEN DEF",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=190",
		"epaisseur": "1.5",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 25,
		"stockage": "Non",
		"page": "I",
		"prix": 29.9
	},
	{
		"categorie": "anti-top",
		"marque": "TIBHAR",
		"designation": "REV. ELLEN OFF",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=191",
		"epaisseur": "1.5/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "I",
		"prix": 29.9
	},
	{
		"categorie": "anti-top",
		"marque": "YASAKA",
		"designation": "REV. ANTI POWER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=320",
		"epaisseur": "2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 28,
		"stockage": "Non",
		"page": "I",
		"prix": 35.9
	},
	{
		"categorie": "anti-top",
		"marque": "NITTAKU",
		"designation": "REV. BEST ANTI",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=551",
		"epaisseur": "1.3/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 30,
		"stockage": "Non",
		"page": "I",
		"prix": 35.9
	},
	{
		"categorie": "anti-top",
		"marque": "DONIC",
		"designation": "REV. ALLIGATOR ANTI",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=793",
		"epaisseur": "1.0/1.5",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 45,
		"stockage": "Non",
		"page": "42",
		"prix": 29.9
	},
	{
		"categorie": "anti-top",
		"marque": "DR NEUBAUER",
		"designation": "REV. POWER ATTACK",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1333",
		"epaisseur": "1.5/1.8/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 36,
		"stockage": "Oui",
		"page": "101",
		"prix": 39
	},
	{
		"categorie": "anti-top",
		"marque": "DR NEUBAUER",
		"designation": "REV. A-B-S 3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1372",
		"epaisseur": "2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42,
		"stockage": "Non",
		"page": "156",
		"prix": 54.9
	},
	{
		"categorie": "anti-top",
		"marque": "DR NEUBAUER",
		"designation": "REV. A-B-S 3 PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1378",
		"epaisseur": "1.3/1.7",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "64",
		"prix": 54.9
	},
	{
		"categorie": "soft",
		"marque": "TIBHAR",
		"designation": "REV. SPEEDY SOFT D TECS XD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=142",
		"epaisseur": "1.5/1.8/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 40,
		"stockage": "Oui",
		"page": "I",
		"prix": 49.9
	},
	{
		"categorie": "soft",
		"marque": "TIBHAR",
		"designation": "REV. SPEEDY SOFT D.TECS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=148",
		"epaisseur": "1.5/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 35,
		"stockage": "Oui",
		"page": "I",
		"prix": 49.9
	},
	{
		"categorie": "soft",
		"marque": "TIBHAR",
		"designation": "REV. SPEEDY SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=180",
		"epaisseur": "1.0/1.5/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": 1,
		"diametrePicot": 2,
		"effetGenant": 1,
		"durete": 45,
		"stockage": "Non",
		"page": "I",
		"prix": 36.9
	},
	{
		"categorie": "soft",
		"marque": "JOOLA",
		"designation": "REV. TANGO ULTRA",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=620",
		"epaisseur": "2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 35,
		"stockage": "Oui",
		"page": "I",
		"prix": 45.9
	},
	{
		"categorie": "soft",
		"marque": "DONIC",
		"designation": "REV. BAXSTER F1-A",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=712",
		"epaisseur": "1.8/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 45.9
	},
	{
		"categorie": "soft",
		"marque": "VICTAS",
		"designation": "REV. SPECTOL S2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=807",
		"epaisseur": "1.6/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 37.5,
		"stockage": "Oui",
		"page": "97",
		"prix": 44.9
	},
	{
		"categorie": "soft",
		"marque": "VICTAS",
		"designation": "REV. SPECTOL S1",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=808",
		"epaisseur": "1.3/1.6/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Non",
		"page": "97",
		"prix": 39.9
	},
	{
		"categorie": "soft",
		"marque": "VICTAS",
		"designation": "REV. SPINPIPS D3",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=815",
		"epaisseur": "0.5/1.0/1.5/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": null,
		"stockage": "Non",
		"page": "97",
		"prix": 39.9
	},
	{
		"categorie": "soft",
		"marque": "ANDRO",
		"designation": "REV. BLOWFISH",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1051",
		"epaisseur": "1.8/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 40,
		"stockage": "Oui",
		"page": "I",
		"prix": 44.95
	},
	{
		"categorie": "soft",
		"marque": "ANDRO",
		"designation": "REV. BLOWFISH+",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1052",
		"epaisseur": "1.8/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 1,
		"durete": 43,
		"stockage": "Oui",
		"page": "I",
		"prix": 44.95
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. KILLER PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1331",
		"epaisseur": "1.3/1.5/1.8/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 2,
		"durete": 45,
		"stockage": "Oui",
		"page": "101",
		"prix": 46
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. KILLER SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1361",
		"epaisseur": "1.3/1.5/1.8/2.0/2.2",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 35,
		"stockage": "Oui",
		"page": "101",
		"prix": 46
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. TORNADO SUPREME",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1363",
		"epaisseur": "1.2/1.5/1.8/2.0/2.2",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Oui",
		"page": "100",
		"prix": 46
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. KILLER EXTREME",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1365",
		"epaisseur": "1.3/1.5/1.8/2.0/max",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 36,
		"stockage": "Oui",
		"page": "100",
		"prix": 46
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. TORNADO SUPREME SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1369",
		"epaisseur": "1.3/1.5/1.8/2.0/2.2",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 33,
		"stockage": "Oui",
		"page": "154",
		"prix": 46
	},
	{
		"categorie": "soft",
		"marque": "DR NEUBAUER",
		"designation": "REV. EXPLOSION SOFT",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1370",
		"epaisseur": "1.3/1.5/1.8/2.0/2.2",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 33,
		"stockage": "Oui",
		"page": "154",
		"prix": 46
	},
	{
		"categorie": "mi long",
		"marque": "DR NEUBAUER",
		"designation": "REV. KO PRO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1348",
		"epaisseur": "1.3/1.5/1.8/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 2,
		"durete": 45,
		"stockage": "Oui",
		"page": "I",
		"prix": 46
	},
	{
		"categorie": "mi long",
		"marque": "DR NEUBAUER",
		"designation": "REV. AGGRESSOR EVO",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1362",
		"epaisseur": "1.3/1.5/1.8/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 44,
		"stockage": "Oui",
		"page": "101",
		"prix": 46
	},
	{
		"categorie": "mi long",
		"marque": "DR NEUBAUER",
		"designation": "REV. KO PRO EXTREME",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1376",
		"epaisseur": "1.3/1.5/1.8/2.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 38,
		"stockage": "Non",
		"page": "64",
		"prix": 46
	},
	{
		"categorie": "long",
		"marque": "TIBHAR",
		"designation": "REV. GRASS D.TECS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=147",
		"epaisseur": "sm/0.5/0.9/1.2/1.6",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 50.9
	},
	{
		"categorie": "long",
		"marque": "TIBHAR",
		"designation": "REV. GRASS D.TECS GS",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=161",
		"epaisseur": "sm",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 47.5,
		"stockage": "Oui",
		"page": "I",
		"prix": 53.9
	},
	{
		"categorie": "long",
		"marque": "DONIC",
		"designation": "REV. PIRANJA CD",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=719",
		"epaisseur": "sm/0.3/1.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 42.5,
		"stockage": "Oui",
		"page": "42",
		"prix": 39.9
	},
	{
		"categorie": "long",
		"marque": "DONIC",
		"designation": "REV. PIRANJA FORMULA TEC",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=745",
		"epaisseur": "sm/1.2",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 50,
		"stockage": "Oui",
		"page": "42",
		"prix": 49.9
	},
	{
		"categorie": "long",
		"marque": "DONIC",
		"designation": "REV. ALLIGATOR DEF",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=755",
		"epaisseur": "sm/0.5/1.0",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 45,
		"stockage": "Non",
		"page": "42",
		"prix": 32.9
	},
	{
		"categorie": "long",
		"marque": "VICTAS",
		"designation": "REV. CURL P4V",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=889",
		"epaisseur": "sm/0.5/1.0/1.5",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": 1.7,
		"diametrePicot": 1.5,
		"effetGenant": 3,
		"durete": null,
		"stockage": "Non",
		"page": "97",
		"prix": 39.9
	},
	{
		"categorie": "long",
		"marque": "VICTAS",
		"designation": "REV. CURL P1V",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=891",
		"epaisseur": "sm/0.5/1.0/1.5",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": 1.75,
		"diametrePicot": 1.6,
		"effetGenant": 3,
		"durete": null,
		"stockage": "Non",
		"page": "97",
		"prix": 39.9
	},
	{
		"categorie": "long",
		"marque": "DR NEUBAUER",
		"designation": "REV. TROUBLE MAKER",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1351",
		"epaisseur": "sm/0.6/1.0/1.3",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 34,
		"stockage": "Non",
		"page": "100",
		"prix": 46
	},
	{
		"categorie": "long",
		"marque": "DR NEUBAUER",
		"designation": "REV. ALLROUND PREMIUM 2",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1352",
		"epaisseur": "sm/0.6/1.0/1.3",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 34,
		"stockage": "Non",
		"page": "100",
		"prix": 42.9
	},
	{
		"categorie": "long",
		"marque": "DR NEUBAUER",
		"designation": "REV. PUNCH",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1373",
		"epaisseur": "sm/0.6/1.0/1.3",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 2,
		"durete": 40,
		"stockage": "Non",
		"page": "155",
		"prix": 42.9
	},
	{
		"categorie": "long",
		"marque": "DR NEUBAUER",
		"designation": "REV. DESPERADO RELOADED",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1375",
		"epaisseur": "sm/0.5/0.6/1.0/1.3",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 0,
		"durete": 36,
		"stockage": "Oui",
		"page": "63",
		"prix": 42.9
	},
	{
		"categorie": "long",
		"marque": "DR NEUBAUER",
		"designation": "REV. TROUBLE MAKER RELOADED",
		"ref": "https://www.wsport.com/catalogue/?todo=aff_items&grp=1377",
		"epaisseur": "sm/0.5/0.6/1.0/1.3",
		"rapidite": null,
		"adherence": null,
		"controle": null,
		"longueurPicot": null,
		"diametrePicot": null,
		"effetGenant": 3,
		"durete": 34,
		"stockage": "Non",
		"page": "63",
		"prix": 42.9
	}
];